spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:1b
      embedding:
        options:
          model: nomic-embed-text:latest
    vectorstore:
      pgvector:
        dimensions: 768
        initialize-schema: true

  datasource:
    url: jdbc:postgresql://localhost:5433/chatbot_db
    username: user
    password: chatbot
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


jwt:
  secret-key: hendbajnendaoienfiaena9n3i3i9jina093je09isk093jmw90j3rjom3o9kaj903je9j3mrn9amsj39aje093jrma9o30